### PR TITLE
added getEps

### PR DESCRIPTION
**Pull request by MiGraber**

### CODE REVIEW

**Comment by tuanle618** [comment]
@MiGraber I merged the branch into master. Please modify https://github.com/ptl93/AEDA/blob/49da9b4b77913465c35dab3015c1a5633a14a8ca/R/makeClusterTask.R#L128 with your function :)

thanks

**Comment by MiGraber** [comment]
With eps foxed to 0.15:
https://github.com/ptl93/AEDA/pull/37#issuecomment-375767415
now:
grafik
grafik
Probably the eps is still not optimal espacially for the comb plot but much better than befor.

**Comment by MiGraber** [comment]
Ready for merging?

**Comment by tuanle618** [comment]
Yes. Please merge

**Pull request merged**
