### PR TITLE
Tle rmdstyle

### PR DESCRIPTION
**Pull request by tuanle618**
Added some markdown function for displaying tables in a better format in output html.

run following code to checkout the results:

`data("Arthritis", package = "vcd")`
`cat.sum.task = makeCatSumTask(id = "Arthritis.Task", data = Arthritis, target = "Improved", na.rm = TRUE)`
`cat.sum = makeCatSum(cat.sum.task)`
`cat.sum.report = makeCatSumReport(cat.sum)`
`data("Boston", package = "MASS")`
`num.sum.task = makeNumSumTask(id = "BostonTask", data = Boston, target = "medv")`
`num.sum = makeNumSum(num.sum.task)`
`num.sum.report = makeNumSumReport(num.sum)`
`finishReport(num.sum.report, cat.sum.report)`

Need further improvements like:

- captioning of tables (with reference)

- captioning of plots (with reference)

- in general code chunk options, e.g: fig.width,...

aditionally to current TOC: ideally table of contents of each (table and plots). Might seperate the code for tables and plots in seperate r-code chunks. As of now pls check and merge. Further styling should be done the next day.

### CODE REVIEW

**Comment by MiGraber** [comment]
I got an error while R Markdown was compiling (with your code):
`Fehler in dn[[2L]] : Indizierung außerhalb der Grenzen
Ruft auf: <Anonymous> ... eval -> print -> kable_styling -> kable -> colnames`
here is the full log: https://pastebin.com/CFCBK4EP

Do you get this error if try your code example with a clean r studio session?

**Comment by tuanle618** [comment]
you might don't have `dpylr` package? I use the pipe operator in a few lines
When I execute it, I dont get any error: https://pastebin.com/UaCuC2Lw

@MiGraber , you might reinstall `kableExtra` and `DT` package

**Comment by MiGraber** [comment]
I installed the needed packages. I try reinstalling and I can use my second pc to see if this makes a difference.

**Comment by MiGraber** [comment]
Ok, after reinstalling its working know.
Looks quite nice.
I assume that you didn't found straight forward solution for displaying
`frac{sum_{i = 1}^{n}(x_i - bar{x})^4 / n}{s^4}`
correctly?

**Comment by MiGraber** [comment]
Ok I have a solution. Latex syntax can be used: `$ equation $`
I will push a "fix" soon

When I knit the main file it automatically open all the 1-D and 2-D Contingency tables in my browser. Does this happen for you too?

**Comment by tuanle618** [comment]
@MiGraber yes, unfortunately the html files pop up in my webbrowser as well.. I didnt have a deep look into it. For the latex equation I tried it as well. It works with bookdown if its in plain text, but in an r-block I got an error for using the string `\s` or something like that. A literal which is used/has a placeholder for something else..(?)

**Comment by MiGraber** [comment]
Ok i dont push it:
grafik
The spacing of the footnote `a` is now off. I'm not sure how we should handle it. Leave it like this, Remove the the footnote layout or dont print the fraction...

The solution was:
`$\\frac{\\sum_{i = 1}^{n}(x_i - \\bar{x})^4 / n}{s^4}$`
I not sure why but it was needed to esacpe the `\`. So you dont get the `\s` escaping error

**Comment by tuanle618** [comment]
I'll use the above solution. I tried to include a colnames footer for kurtosis, skewness, l.bound and u.bound. Code is included but it doesnt work somehow. i'll merge the branch the next days and try to improve the styling

headers_fnote

**Comment by MiGraber** [comment]
Ok looks good. I would say merge and open issue for tables opening in browser.
Can you explain why there four backslashes?

**Comment by tuanle618** [comment]
@MiGraber : ok will merge. Issue will be opened after that.
Hmm when only using two backslashes the written text in .rmd file is only \f \sum... and then threw an error.

**Pull request merged**
