### PR TITLE
Tle cluster 

### PR DESCRIPTION
**Pull request by tuanle618**
Basic `makeClusterTask()` and `makeClusterAnalysis()` finished. 
I will create a new branch and rewrite all `make*Report()`function and change them as S3-Method. Then will go on with `makeReport` for the `clusterAnalysisObj` and `writeReport*` function.

For testing have a look at this: https://pastebin.com/HgAeAqNN

### CODE REVIEW

**Comment by MiGraber** [comment]
I pushed the missing imports. Hopefully this doesnt interfere with your work.

When loading the package we get several character(0) warnings. The reason seems to be problems with loading the namespace which is not properly shown: https://github.com/r-lib/pkgload/issues/39
So we should use `@importFrom pgk fun` in the roxygen comments and only `@import` if wee need several functions

About the functionality:

for `cluster.dbscan` Plot looks differenz than the others.(Only black dots)
for `cluster.kkmeans` I get : 
```
Error in ggscatter(data = proc.data, x = "PC1", y = "PC2", color = "cluster",  : 
  could not find function "ggscatter"
```

**Comment by tuanle618** [comment]
Ok thanks. Yes that'd be better indeed. I'll change the roxygen comments for import for my functions later.

**Comment by MiGraber** [comment]
The issue i referenced seems to be closed. So let us know if changing @import solves the character(0) warnings

**Comment by tuanle618** [comment]
Thanks @MiGraber. I will change roxygen headers for imports today and try if it resolved the `warnings message character(0)` problem.

**Comment by MiGraber** [comment]
One character(0) warning was already in the master branch. After setting up travis, where I changed imports for some funkctins, this issue didn't occur anymore:
https://github.com/ptl93/AEDA/pull/32/commits/1a6ad1e4dbfb3a5297bde5d0acc80bb59c615a71#diff-81f75a53b5f61cbfa74d5047478b5197
https://github.com/ptl93/AEDA/pull/32/commits/541399af813d36d77c4018d0f8f55d3159516008#diff-12d995d32cf5f08a90397c515c9f1ed8
So I guess this indeed was the cause.

**Pull request merged**
